/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author carlos
 */
public class Vista_Farmacia extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Farmacia
     */
    public Vista_Farmacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_distribuidora = new javax.swing.ButtonGroup();
        dialog_informacion = new javax.swing.JDialog();
        labe_titulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_pedido = new javax.swing.JTextArea();
        label_direccion = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nomb_medi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combo_medicamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radio_cofarma = new javax.swing.JRadioButton();
        radio_empsephar = new javax.swing.JRadioButton();
        radio_cmefar = new javax.swing.JRadioButton();
        cheack_principal = new javax.swing.JCheckBox();
        check_sucursal = new javax.swing.JCheckBox();
        btn_guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_farmacia = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblcount = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Pedido");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Direccion");

        text_pedido.setColumns(20);
        text_pedido.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        text_pedido.setForeground(new java.awt.Color(102, 0, 102));
        text_pedido.setRows(5);
        jScrollPane1.setViewportView(text_pedido);

        label_direccion.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        label_direccion.setForeground(new java.awt.Color(102, 0, 102));

        btn_confirmar.setText("Confirmar");

        btn_cancelar.setText("cancelar");

        javax.swing.GroupLayout dialog_informacionLayout = new javax.swing.GroupLayout(dialog_informacion.getContentPane());
        dialog_informacion.getContentPane().setLayout(dialog_informacionLayout);
        dialog_informacionLayout.setHorizontalGroup(
            dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_informacionLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_informacionLayout.createSequentialGroup()
                        .addGroup(dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labe_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialog_informacionLayout.createSequentialGroup()
                        .addComponent(btn_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        dialog_informacionLayout.setVerticalGroup(
            dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_informacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labe_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(dialog_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirmar)
                    .addComponent(btn_cancelar))
                .addGap(48, 48, 48))
        );

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Nombre del Medicamento");

        txt_nomb_medi.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txt_nomb_medi.setForeground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tipo de Medicamento");

        combo_medicamento.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        combo_medicamento.setForeground(new java.awt.Color(102, 0, 102));
        combo_medicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciones una opcion", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));
        combo_medicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_medicamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Cantidad");

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(102, 0, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Distibuidora");

        grupo_distribuidora.add(radio_cofarma);
        radio_cofarma.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        radio_cofarma.setForeground(new java.awt.Color(102, 0, 102));
        radio_cofarma.setText("COFARMA");
        radio_cofarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_cofarmaActionPerformed(evt);
            }
        });

        grupo_distribuidora.add(radio_empsephar);
        radio_empsephar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        radio_empsephar.setForeground(new java.awt.Color(102, 0, 102));
        radio_empsephar.setText("EMPSEPHAR ");

        grupo_distribuidora.add(radio_cmefar);
        radio_cmefar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        radio_cmefar.setForeground(new java.awt.Color(102, 0, 102));
        radio_cmefar.setText("CEMEFAR");

        cheack_principal.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cheack_principal.setForeground(new java.awt.Color(102, 0, 102));
        cheack_principal.setText("Farmacia Principal");

        check_sucursal.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        check_sucursal.setForeground(new java.awt.Color(102, 0, 102));
        check_sucursal.setText("Sucursal");

        btn_guardar.setText("Guardar");

        tabla_farmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Cantidad", "distribuidora", "Direccion"
            }
        ));
        jScrollPane2.setViewportView(tabla_farmacia);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Pedido Farmacia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nomb_medi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_cofarma, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio_empsephar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(radio_cmefar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combo_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(cheack_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(check_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblcount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nomb_medi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(combo_medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radio_cofarma)
                    .addComponent(radio_empsephar)
                    .addComponent(radio_cmefar))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheack_principal)
                    .addComponent(check_sucursal))
                .addGap(26, 26, 26)
                .addComponent(btn_guardar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcount, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void combo_medicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_medicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_medicamentoActionPerformed

    private void radio_cofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_cofarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_cofarmaActionPerformed

    public JButton getBtn_guardar() {
        return btn_guardar;
    }

    public void setBtn_guardar(JButton btn_guardar) {
        this.btn_guardar = btn_guardar;
    }

   

    public JCheckBox getCheack_principal() {
        return cheack_principal;
    }

    public void setCheack_principal(JCheckBox cheack_principal) {
        this.cheack_principal = cheack_principal;
    }

    public JLabel getLabe_titulo() {
        return labe_titulo;
    }

    public void setLabe_titulo(JLabel labe_titulo) {
        this.labe_titulo = labe_titulo;
    }

    
    public JCheckBox getCheck_sucursal() {
        return check_sucursal;
    }

    public void setCheck_sucursal(JCheckBox check_sucursal) {
        this.check_sucursal = check_sucursal;
    }

    public JComboBox<String> getCombo_medicamento() {
        return combo_medicamento;
    }

    public void setCombo_medicamento(JComboBox<String> combo_medicamento) {
        this.combo_medicamento = combo_medicamento;
    }

    public JDialog getDialog_informacion() {
        return dialog_informacion;
    }

    public void setDialog_informacion(JDialog dialog_informacion) {
        this.dialog_informacion = dialog_informacion;
    }

    public ButtonGroup getGrupo_distribuidora() {
        return grupo_distribuidora;
    }

    public void setGrupo_distribuidora(ButtonGroup grupo_distribuidora) {
        this.grupo_distribuidora = grupo_distribuidora;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getLblcount() {
        return lblcount;
    }

    public void setLblcount(JLabel lblcount) {
        this.lblcount = lblcount;
    }
    

    public JRadioButton getRadio_cmefar() {
        return radio_cmefar;
    }

    public void setRadio_cmefar(JRadioButton radio_cmefar) {
        this.radio_cmefar = radio_cmefar;
    }

    public JRadioButton getRadio_cofarma() {
        return radio_cofarma;
    }

    public JButton getBtn_cancelar() {
        return btn_cancelar;
    }

    public JTable getTabla_farmacia() {
        return tabla_farmacia;
    }

    public void setTabla_farmacia(JTable tabla_farmacia) {
        this.tabla_farmacia = tabla_farmacia;
    }

    
    public void setBtn_cancelar(JButton btn_cancelar) {
        this.btn_cancelar = btn_cancelar;
    }

    public JButton getBtn_confirmar() {
        return btn_confirmar;
    }

    public void setBtn_confirmar(JButton btn_confirmar) {
        this.btn_confirmar = btn_confirmar;
    }

    public JLabel getLabel_direccion() {
        return label_direccion;
    }

    public void setLabel_direccion(JLabel label_direccion) {
        this.label_direccion = label_direccion;
    }

    public JTextArea getText_pedido() {
        return text_pedido;
    }

    public void setText_pedido(JTextArea text_pedido) {
        this.text_pedido = text_pedido;
    }
    
    

    public void setRadio_cofarma(JRadioButton radio_cofarma) {
        this.radio_cofarma = radio_cofarma;
    }

    public JRadioButton getRadio_empsephar() {
        return radio_empsephar;
    }

    public void setRadio_empsephar(JRadioButton radio_empsephar) {
        this.radio_empsephar = radio_empsephar;
    }

   

    public JTextField getTxt_cantidad() {
        return txt_cantidad;
    }

    public void setTxt_cantidad(JTextField txt_cantidad) {
        this.txt_cantidad = txt_cantidad;
    }

    public JTextField getTxt_nomb_medi() {
        return txt_nomb_medi;
    }

    public void setTxt_nomb_medi(JTextField txt_nomb_medi) {
        this.txt_nomb_medi = txt_nomb_medi;
    }

 
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JCheckBox cheack_principal;
    private javax.swing.JCheckBox check_sucursal;
    private javax.swing.JComboBox<String> combo_medicamento;
    private javax.swing.JDialog dialog_informacion;
    private javax.swing.ButtonGroup grupo_distribuidora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labe_titulo;
    private javax.swing.JLabel label_direccion;
    private javax.swing.JLabel lblcount;
    private javax.swing.JRadioButton radio_cmefar;
    private javax.swing.JRadioButton radio_cofarma;
    private javax.swing.JRadioButton radio_empsephar;
    private javax.swing.JTable tabla_farmacia;
    private javax.swing.JTextArea text_pedido;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_nomb_medi;
    // End of variables declaration//GEN-END:variables
}
